### ISSUE TITLE
Deleting a file throws "Cannot read property 'toString' of null" 

### ISSUE THREAD

**Issue by adrianjonmiller** [FormidableLabs/gulp-html-extract#11]
On deleting a file I get this issue.

This is my gulp task:
```
gulp.task('extract:liquid', ['clean:html'], function () {
  return watch(src, {ignoreInitial: false})
    .pipe(plumber())
    .pipe(extract({
      sel: "#template",
      strip: true
    }))
    .pipe(nunjucks.compile({}))
    .pipe(rename(function (path) {
      path.extname = ".html"
    }))
    .pipe(gulp.dest('_site/'))
    .pipe(browserSync.reload({stream: true}));
})
```

![image](https://cloud.githubusercontent.com/assets/3914086/24766924/0490d076-1ab2-11e7-95f5-a4c8d70e99e8.png)

**Comment by ryan-roemer** [comment]
We can certainly throw a guard around `file.contents.toString()`, and then I'm guessing the behavior should be "no entities are extracted" (?)

**Comment by adrianjonmiller** [comment]
Yes that sounds right to me based on a cursory look at the file. My concern was that it was something deeper about how the gulp pipe handled file deletion.

**Comment by ryan-roemer** [comment]
@adrianjonmiller -- Can you pull down https://github.com/FormidableLabs/gulp-html-extract/pull/12 and verify it fixes your problem? Thanks!
