### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by felixzapata** [FormidableLabs/gulp-html-extract#2]
Hi, when I try to use the task in Windows system, throws me an error related with `jsdom` package.

[This package is very problematic under Windows](http://stackoverflow.com/questions/17097179/npm-not-installing-jsdom-in-windows). Sometimes is difficult to install it and when you achieve this, the parser does not work fine. 

Maybe it is possible to use `jsdom-little` or `cheerio` .

**Comment by ryan-roemer** [comment]
@felixzapata -- Thanks for the issue! Could you open a PR with a different library that works for you?

**Comment by felixzapata** [comment]
I just made a fork to try to use another package instead of `jsdom`.

**Comment by ryan-roemer** [comment]
New version `v0.0.2` has `cheerio` PR integrated and now has appveyor CI to ensure that the project builds and runs on Windows.
